project : "lancelot"
environment: "staging"
squad: "ml"
name: "redis"

containers:
  image:
  repository: "docker.io/redis"
  tag: "6.0.5"

service:
  type: ClusterIP
  port: 6379

ingress:
  enabled: false
resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi