name: CI

on:
  push:
    paths:
      - '*/*/*.yaml'

    branches:
      - main

  pull_request:
    branches:
      - "*"
    paths:
      - '*/*/*.yaml'

jobs:
    dry-run:
      runs-on: ubuntu-latest
      
      steps:
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Helm Dry Run
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          EKS_STAGING_CA: ${{ secrets.EKS_STAGING_CA }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
        run: |
          changes=$(git diff --diff-filter=ACMRT --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} */*/*.yaml)
          make kubeconfig
          make plan
      

    deploy: 
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest

      steps: 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to cluster
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          EKS_STAGING_CA: ${{ secrets.EKS_STAGING_CA }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
        run: |
          make kubeconfig deploy

      


