name: CI

on:
  push:
    paths:
      - '**'

    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
    test:
      runs-on: ubuntu-latest
      
      steps:
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: install dependency
        run: |
         pip install -r sample-app/requirements.txt
         python3 sample-app/app/test.py


    deploy: 
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest

      steps: 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build & push docker images
        shell: bash
        run: |
          make build push

      - name: deploy to cluster
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CA_CRT: ${{ secrets.CA_CRT }}
        run: |
          export SA_TOKEN=$(echo $SERVICE_ACCOUNT | base64 -d)
          echo $CA_CRT | base64 -d > /tmp/ca.crt
          make kubeconfig deploy

      


