name: CI

permissions:
  id-token: write
  contents: read
  
on:
  push:
    paths:
      - '*/*/*.yaml'

    branches:
      - main

  pull_request:
    branches:
      - "*"
    paths:
      - '*/*/*.yaml'

jobs:
    dry-run:
      if: ${{ github.ref != 'refs/heads/main' }}
      runs-on: ubuntu-latest
      container:
          image: venter/kubetools:v1.0.0
          options: --user root
      
      steps:

      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Helm Dry Run
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          EKS_STAGING_CA: ${{ secrets.EKS_STAGING_CA }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          EKS_ADDRESS: ${{ secrets.EKS_ADDRESS }}
        shell: bash
        run: |
          export changes=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} --diff-filter=ACMRT --name-only */*/*.yaml)
          make kubeconfig plan
      

    deploy: 
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest
      container:
          image: venter/kubetools:v1.0.0
          options: --user root

      steps: 
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to cluster
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          EKS_STAGING_CA: ${{ secrets.EKS_STAGING_CA }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          EKS_ADDRESS: ${{ secrets.EKS_ADDRESS }}
        shell: bash
        run: |
          export changes=$(git diff HEAD^ HEAD --diff-filter=ACMRT --name-only */*/*.yaml | xargs)
          make kubeconfig deploy

      


