name: rollback

on: workflow_dispatch

jobs:
    rollback:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Helm Rollback
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CA_CRT: ${{ secrets.CA_CRT }}
        run: |
          export SA_TOKEN=$(echo $SERVICE_ACCOUNT | base64 -d)
          echo $CA_CRT | base64 -d > /tmp/ca.crt
          make kubeconfig rollback
